name: "Deploy"
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: Upload Next App
        uses: actions/upload-artifact@v4
        with:
          name: nextApp
          path: apps/web/dist
      - name: Upload server
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: apps/server/dist

  deployApp:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: download nextApp
        uses: actions/download-artifact@v4
        with:
          name: nextApp
          path: apps/web/dist
      - name: Upload to zapworks
        run: "npx zapworks upload --version 0.1.0 --project 188036643207967500 --dir apps/web/dist"
  deployServer:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: download server
        uses: actions/download-artifact@v4
        with:
          name: server
          path: apps/server/dist
      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "apps/server/dist/"
          target: "/var/www/html/AquariumServer/"
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          key: ${{ secrets.SSHKEY }}
          script: |
            cd /var/www/html/AquariumServer/
            pm2 restart AquariumServer
